### PR TITLE
Updated Clickable coords

### PR DESCRIPTION
**Pull request by superjeffc**
This pull request fixes the coordinates and colors of a few enums in the Clickable class because the TH11 update changed a lot of the artwork in the game. This should fix the issue of the bot getting stuck in several states.

### CODE REVIEW

**Comment by frpedraya88** [comment]
hey there @superjeffreyc can you tell me how to update the bot please? im not good in that kind stuff so can you please be specific on telling how to update them? thanks godbless

**Comment by superjeffc** [comment]
I wanted to wait for @norecha to take a look at this request first. If he agrees with the changes, he will most likely release a new update with the changes.

**Comment by norecha** [comment]
@superjeffreyc thanks for the PR. Actually I was in the middle of release process right now, I had already updated those values :/

**Comment by frpedraya88** [comment]
yes! can't wait for the release.....

**Pull request closed without merging**
